'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.ACP

    Partial Public Class ForumEdit

        '''<summary>
        '''ACPmenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ACPmenu As Global.DotNetNuke.Modules.Forum.ACP.Menu


        '''<summary>
        '''txtForumID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtForumID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plEnableForum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableForum As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plGroupName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plGroupName As Global.System.Web.UI.UserControl

        '''<summary>
        '''rcbGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbGroup As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''rowParentForum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowParentForum As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plParentForumName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plParentForumName As Global.System.Web.UI.UserControl

        '''<summary>
        '''rcbParentForum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbParentForum As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''plForumName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumName As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtForumName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtForumName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plForumDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumDescription As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtForumDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtForumDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plForumType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumType As Global.System.Web.UI.UserControl

        '''<summary>
        '''rcbForumType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbForumType As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''rowForumBehavior control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowForumBehavior As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plForumBehavior control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumBehavior As Global.System.Web.UI.UserControl

        '''<summary>
        '''rcbForumBehavior control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbForumBehavior As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''rowPolls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowPolls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plAllowPolls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAllowPolls As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkAllowPolls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowPolls As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowThreadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowThreadStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableForumsThreadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableForumsThreadStatus As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableForumsThreadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableForumsThreadStatus As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowRating As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableForumsRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableForumsRating As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableForumsRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableForumsRating As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowEnableRSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowEnableRSS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableRSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableRSS As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableRSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableRSS As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowEnableSitemap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowEnableSitemap As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableSitemap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableSitemap As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableSitemap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableSitemap As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rowSitemapPriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowSitemapPriority As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plSitemapPriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSitemapPriority As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSitemapPriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSitemapPriority As Global.Telerik.Web.UI.RadNumericTextBox

        '''<summary>
        '''rowPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowPermissions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''dgPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgPermissions As Global.DotNetNuke.Modules.Forum.Controls.ForumPermissionsGrid

        '''<summary>
        '''lblPrivateNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrivateNote As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plForumPermTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumPermTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''rcbForumPermTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbForumPermTemplate As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''rowForumLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowForumLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rowLinkTracking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowLinkTracking As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailAddress As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAddy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAddy As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valEmailAddy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmailAddy As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plEmailFriendlyFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailFriendlyFrom As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtEmailFriendlyFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailFriendlyFrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDisplay As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''divHidden control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divHidden As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plNotifyByDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNotifyByDefault As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkNotifyByDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNotifyByDefault As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plEmailStatusChange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailStatusChange As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEmailStatusChange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEmailStatusChange As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plEmailServer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailServer As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtEmailServer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailServer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plEmailUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailUser As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtEmailUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailUser As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plEmailPass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailPass As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtEmailPass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailPass As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plEmailPort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailPort As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtEmailPort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailPort As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plEmailEnableSSL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailEnableSSL As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEmailEnableSSL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEmailEnableSSL As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plEmailAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailAuth As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlEmailAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEmailAuth As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ctlAudit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlAudit As Global.DotNetNuke.UI.UserControls.ModuleAuditControl

        '''<summary>
        '''cmdHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdHome As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
